menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/leizhang233
    GitHub: https://github.com/zhanglei12345
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: https-zhanglei12345-github-io
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2015
